# User
DEVICE: cuda
BATCH_SIZE: 2

# NOTE: the ith class will be published to the ith prob_topic
CLASSES:
  - traversable
  - untraversable
  - obstacle

PROB_TOPICS:
  - /ovt/c1_probs
  - /ovt/c1_probs
  - /ovt/c1_probs

# ROS
ROBOT_IMAGE_TOPIC: /wide_angle_camera_front/image_color_rect/compressed
CLASS_TOPIC: classes_topic
IMAGE_TOPIC: image_topic
RESET_TOPIC: reset_topic
CHANGE_BUFFER_SIZE_TOPIC: change_buffer_size
CHANGE_RATE_TOPIC: change_rate

REQUEST_SERVICE: request_computation

SERVER_NODE: backend
DATA_INTERFACE_NODE: data_interface
